### ISSUE TITLE
TryBuild restore: true and using projectCollection causes Build to be not isolated from "Restore"?

### ISSUE THREAD

**Issue by japj** [jeffkl/MSBuildProjectCreator#132]
Hi,

From inspecting the binlog of a failed testcase, it looks as if I am seeing the following problem:

Scenario:
- csproj containing a PackageReference containing MSBuild targets/props
- run TryBuild restore:true with a projectCollection

Result:
- Build fails because it did not run the logic from the NuGet package targets/props

In the binlog I see only one project evaluation of the test project (the evaluation related to the Restore).
And I see the "build" targets underneath the tree of the Restore target instead of in its own project tree.

Since the Restore is generating NuGet.g.props/targets it means that when it runs the actual build it should do a re-evaluation of the test csproj file (since the global properties are different due to ExcludeRestorePackageImports), but that does not seem to happen.

Note this is something that I'm experiencing after upgrading to Visual Studio 2019 Update 11 from Update 9 (with 
MSBuildProjectCreator 6.3.1)

I see that when no projectCollection is passed in Restore it will create a new collection, perhaps this is issue is related to that logic?
https://github.com/jeffkl/MSBuildProjectCreator/blob/881f1f62350c1f3633ee084cd3666272e2695c13/src/Microsoft.Build.Utilities.ProjectCreation/ProjectCreator.Build.cs#L532

As a workaround if I do

```c#
                    .TryBuild(target:"Restore", out result, out buildOutput) // workaround Restore isolation issue
                    .TryBuild(out result, out buildOutput);
```

Instead of
```c#
                     .TryBuild(restore: true, out result, out buildOutput);
```

It seems to work ok (i.e. no test failure)

**Comment by japj** [comment]
I am also noting some other weird errors that might indicate that using projectCollection global properties does not seem to work.

**Comment by japj** [comment]
I tested 6.3.1, 6.3.0 and 6.2.4 and it seems the global properties issue was introduced in 6.3.0 (6.2.4 works fine).

Perhaps https://github.com/jeffkl/MSBuildProjectCreator/commit/881f1f62350c1f3633ee084cd3666272e2695c13 broke this behavior in some weird way?

**Comment by jeffkl** [comment]
Interesting, I'm surprised no unit test caught this.  Let me see if I can add one that shows the broken behavior...

**Comment by jeffkl** [comment]
Alright the problem was caused by removing this:

https://github.com/jeffkl/MSBuildProjectCreator/commit/47cb8d3705b17b1427fb66692d9d6aa8dfc140d1#diff-e9c40f69d5dc156538cdc2b04b41e1d10d80faede62691b69838d3e46fb9b821L561

It used to pass `null` to Restore which would make a new global property collection.  The new code takes the global property collection and modifies it so that the properties are now the same for restore and build which causes MSBuild to not re-evaluate the project.

I think it was a bug that Restore didn't use specified global properties for Restore so I'm going to just make a copy of the global properties for restore so they aren't modifying the set used for Build.

Thanks for reporting this!
