### ISSUE TITLE
Referencing a local `.nupkg`

### ISSUE THREAD

**Issue by slang25** [jeffkl/MSBuildProjectCreator#210]
Hello 👋 

I'm trying out this library for the first time, and I'm trying to figure out if there's an elegant way to take a local `.nupkg` file and add a `PackageReference` to it.

I'm looking at the API, and what I think I want is something roughly like this:
```csharp
// some code to move a `MyPackage.1.0.0.nupkg` file into the rootPath directly.
// and then...
PackageFeed.Create(rootPath)
    .GetPackage("MyPackage", "1.0.0", out var package);

ProjectCreator
    .Templates.SdkCsproj()
    .ItemPackageReference(package)
    .Save();
```

Is there a good way to do this, or am I trying to do something that this library wasn't designed to do?

**Comment by jeffkl** [comment]
Well I had to push a change to make this work but now it's possible with version 10.0.0.  You'll still want to create a `PackageRepository` so you can isolate things.  Otherwise this local package could pollute your global package repository.

https://github.com/jeffkl/MSBuildProjectCreator#add-a-local-directory-as-a-feed

So you create a PackageRepository that points to the directory that contains your package.  At this time, you'll need to specify the package ID and version as strings.  Also, if your package has dependencies, make sure they're in the same directory or you add each directory containing packages as feeds to the PackageRepository.  Let me know if you have any issues!

**Comment by slang25** [comment]
That's works just as I'd hoped. Thanks @jeffkl, what a great little library!
