### ISSUE TITLE
TryBuild fails on plain sdk project build

### ISSUE THREAD

**Issue by MeikTranel** [jeffkl/MSBuildProjectCreator#31]
The following
```csharp
ProjectCreator.Templates.SdkCsproj("test.csproj", targetFramework: "netstandard2.0")
  .Save()
  .TryBuild(out var result, out var buildOutput);
```
fails with the following error:
```
Assets file 'D:\X\bin\Debug\net472\3226627f\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.
```

I assume this happens because sdk-based builds require either a separate `nuget restore` or a `msbuild /restore` when building for the first time. `dotnet build` does wrap all that stuff already i assume.
I've been searching for ways  to attach the /restore flag myself but `Directory.Build.rsp` fails and i see no option inside ProjectInstance etc. to run this as well.

**Comment by jeffkl** [comment]
The only way to replicate the `/restore` logic is to build twice with two different instances of the project.  This is done with different global properties:

```C#
ProjectCollection projectCollection = new ProjectCollection(globalProperties: new Dictionary<string, string>
{
    ["MSBuildRestoreSessionId"] = Guid.NewGuid().ToString("D"),
});

string path = GetTempFileName(".csproj");

const string targetFramework = "net472";

ProjectCreator.Templates.SdkCsproj(
        targetFramework: targetFramework,
        projectCollection: projectCollection)
    .Save(path)
    .TryBuild("Restore", out bool restoreResult, out BuildOutput restoreBuildOutput);

restoreResult.ShouldBeTrue(restoreBuildOutput.GetConsoleLog());

ProjectCreator.Templates.SdkCsproj(
        targetFramework: targetFramework)
    .Save(path)
    .TryBuild("Build", out bool result, out BuildOutput buildOutput);

result.ShouldBeTrue(buildOutput.GetConsoleLog());
```

We could add a convenience method for the above if needed.

I mostly use MSBuild.ProjectCreation for unit tests so I don't actually need things to build.  So I disable the usage of NuGet assets by faking a design time build:

```C#
ProjectCollection projectCollection = new ProjectCollection(globalProperties: new Dictionary<string, string>
{
    ["DesignTimeBuild"] = "true"
});

const string targetFramework = "net472";

ProjectCreator.Templates.SdkCsproj(
        targetFramework: targetFramework,
        path: GetTempFileName(".csproj"),
        projectCollection: projectCollection)
    .Save()
    .TryBuild("Build", out bool result, out BuildOutput buildOutput);

result.ShouldBeTrue(buildOutput.GetConsoleLog());
```

**Comment by MeikTranel** [comment]
Conviencemethod sounds convenient 😄

**Comment by jeffkl** [comment]
You don't have to set a particular property, you just need the evaluation for the Restore target to be different than the evaluation for the Build target.  The easiest way to do this is to use two different sets of global properties.  This is because you want the project instance for Build to be re-evaluated in case it builds in imports from the packages.  Without different global properties, MSBuild will re-use the project from restore which could be invalid.

I picked [MSBuildRestoreSessionId](https://github.com/Microsoft/msbuild/blob/master/src/MSBuild/XMake.cs#L1339) when implementing `/restore`.  But you can specify anything as long as the overall global properties are different between Restore and Build.

**Comment by MeikTranel** [comment]
Hey any chance we can get this in a release?

**Comment by jeffkl** [comment]
https://www.nuget.org/packages/MSBuild.ProjectCreation/1.2.20
